[DRV8830]
x = [4, 97]
y = [5, 99]
z = [6, 100]

[MMC]
# channels for each sensor
s1 = 1
s2 = 2
s3 = 3

[MUX]
path = "/dev/i2c-1"

[GAINS]
xyz = [0.30, 0.30, 0.34]
xyz_ohms = [25.0, 25.0, 27.0]

[CALS]
s1 = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0] # 9 dobule array for calibration and rotation of values
s2 = [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, -1.0, 0.0]
s3 = [1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, -1.0]

[FILTER]
w = [0.1, 0.25, 0.3, 0.35]  # array of max length

[TESTING]
target = "127.0.0.1"
port = 7777

[MISC]
rate = 0.1
