[DEPLOY]
csp_service_id = 20
req_fmt_str = "<?h"
res_fmt_str = "<?h"
TIMEOUT = 10000

[STEPPER] 
csp_service_id = 21
req_fmt_str = "<f?h"     # float dist, bool - brake direction
res_fmt_str = "<fHh"     # float dist completed, H - char # faults
TIMEOUT = 20000

[ARM]
csp_service_id = 22
req_fmt_str = "<10ph"    # 10 character pascal string password | spam count
res_fmt_str = "<?h"      # true/false for password verification and arming | spam count
TIMEOUT = 10000

[ERROR]
msg_fmt_str = "<hh"      # error code | spam } both are char numbers (h)
TIMEOUT = 1000
# BINARY COMMANDS
[BIN]
csp_service_id = 23
req_fmt_str = "<hh"
TIMEOUT = 8000

[BIN.SystemInfo]
res_fmt_str = "<fii?????fffffffffffffffffffff"
command_id = 0
TIMEOUT = 50000

[BIN.PING]
res_fmt_str = "<15ph"
command_id = 1
TIMEOUT = 5000

[BIN.BDOT]
res_fmt_str = "<fffh"
command_id = 2
TIMEOUT = 8000

[BIN.CTRL]
res_fmt_str = "<?h"
command_id = 3
TIMEOUT = 5000

[BIN.EPSRESET]
res_fmt_str = "<?"
command_id = 4
TIMEOUT = 5000


